// Package candidates provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package candidates

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Account defines model for Account.
type Account struct {
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
	Id       int64  `json:"id"`
	IdUser   int64  `json:"id_user"`
}

// Error defines model for Error.
type Error struct {
	// Code Код ошибки приложения
	Code int32 `json:"code"`

	// Message Сообщение об ошибке
	Message string `json:"message"`

	// Status HTTP статус код
	Status int `json:"status"`
}

// GetAccountsResponse defines model for GetAccountsResponse.
type GetAccountsResponse struct {
	Accounts []Account `json:"accounts"`
}

// GetUsersByID defines model for GetUsersByID.
type GetUsersByID struct {
	Accounts GetAccountsResponse `json:"accounts"`
	User     User                `json:"user"`
}

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse struct {
	Users []User `json:"users"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse = Error

// User defines model for User.
type User struct {
	Id          *int64 `json:"id,omitempty"`
	Mail        string `json:"mail"`
	Name        string `json:"name"`
	PhoneNumber string `json:"phone_number"`
}

// Limit defines model for Limit.
type Limit = int32

// UserMail defines model for UserMail.
type UserMail = string

// UserName defines model for UserName.
type UserName = string

// UserPhoneNumber defines model for UserPhoneNumber.
type UserPhoneNumber = string

// UserId defines model for User_id.
type UserId = int64

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Name Имя
	Name *UserName `form:"name,omitempty" json:"name,omitempty"`

	// PhoneNumber Номер телефона
	PhoneNumber *UserPhoneNumber `form:"phone_number,omitempty" json:"phone_number,omitempty"`

	// Mail Почта
	Mail *UserMail `form:"mail,omitempty" json:"mail,omitempty"`

	// Limit Ограничение количества пользователей
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = User

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = User

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение списка пользователей
	// (GET /users)
	GetUsers(c *gin.Context, params GetUsersParams)
	// Создание пользователя
	// (POST /users)
	CreateUser(c *gin.Context)
	// Получение пользователя по айди
	// (GET /users/user/{id})
	GetUserByID(c *gin.Context, id UserId)
	// Обновление данных пользователя
	// (PUT /users/{id})
	UpdateUser(c *gin.Context, id UserId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "phone_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "phone_number", c.Request.URL.Query(), &params.PhoneNumber)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter phone_number: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "mail" -------------

	err = runtime.BindQueryParameter("form", true, false, "mail", c.Request.URL.Query(), &params.Mail)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter mail: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c, params)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// GetUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetUserByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserByID(c, id)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
	router.GET(options.BaseURL+"/users/user/:id", wrapper.GetUserByID)
	router.PUT(options.BaseURL+"/users/:id", wrapper.UpdateUser)
}
