// Package candidates provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package candidates

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Account defines model for Account.
type Account struct {
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
	Id       *int64 `json:"id,omitempty"`
	IdUser   *int64 `json:"id_user,omitempty"`
}

// DepAccount defines model for DepAccount.
type DepAccount struct {
	// Dep Сумма пополнения
	Dep int32 `json:"dep"`
}

// Error defines model for Error.
type Error struct {
	// Code Код ошибки приложения
	Code int32 `json:"code"`

	// Message Сообщение об ошибке
	Message string `json:"message"`

	// Status HTTP статус код
	Status int `json:"status"`
}

// GetAccountsByID defines model for GetAccountsByID.
type GetAccountsByID struct {
	Account Account `json:"account"`
}

// GetAccountsResponse defines model for GetAccountsResponse.
type GetAccountsResponse struct {
	Accounts []Account `json:"accounts"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse = Error

// AccountUserId defines model for AccountUser_id.
type AccountUserId = int64

// AccountId defines model for Account_id.
type AccountId = int64

// DepAccountJSONRequestBody defines body for DepAccount for application/json ContentType.
type DepAccountJSONRequestBody = DepAccount

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = Account

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Пополнение счета
	// (POST /accounts/dep/{id})
	DepAccount(c *gin.Context, id AccountId)
	// Получение списка счетов пользователя
	// (GET /accounts/user/{id_user})
	GetAccounts(c *gin.Context, idUser AccountUserId)
	// Создание счета
	// (POST /accounts/user/{id_user})
	CreateAccount(c *gin.Context, idUser AccountUserId)
	// Удаление счета
	// (DELETE /accounts/{id})
	DeleteAccount(c *gin.Context, id AccountId)
	// Получение счета по айди
	// (GET /accounts/{id})
	GetAccountByID(c *gin.Context, id AccountId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DepAccount operation middleware
func (siw *ServerInterfaceWrapper) DepAccount(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id AccountId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DepAccount(c, id)
}

// GetAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAccounts(c *gin.Context) {

	var err error

	// ------------- Path parameter "id_user" -------------
	var idUser AccountUserId

	err = runtime.BindStyledParameter("simple", false, "id_user", c.Param("id_user"), &idUser)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id_user: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccounts(c, idUser)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(c *gin.Context) {

	var err error

	// ------------- Path parameter "id_user" -------------
	var idUser AccountUserId

	err = runtime.BindStyledParameter("simple", false, "id_user", c.Param("id_user"), &idUser)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id_user: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAccount(c, idUser)
}

// DeleteAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAccount(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id AccountId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAccount(c, id)
}

// GetAccountByID operation middleware
func (siw *ServerInterfaceWrapper) GetAccountByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id AccountId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountByID(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/accounts/dep/:id", wrapper.DepAccount)
	router.GET(options.BaseURL+"/accounts/user/:id_user", wrapper.GetAccounts)
	router.POST(options.BaseURL+"/accounts/user/:id_user", wrapper.CreateAccount)
	router.DELETE(options.BaseURL+"/accounts/:id", wrapper.DeleteAccount)
	router.GET(options.BaseURL+"/accounts/:id", wrapper.GetAccountByID)
}
