// Code generated by MockGen. DO NOT EDIT.
// Source: account.go

// Package repo is a generated GoMock package.
package repo

import (
	domain "Roman_Sakutin/Roman_Sakutin/8-Service/Bank/internal/model/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccounts is a mock of Accounts interface.
type MockAccounts struct {
	ctrl     *gomock.Controller
	recorder *MockAccountsMockRecorder
}

// MockAccountsMockRecorder is the mock recorder for MockAccounts.
type MockAccountsMockRecorder struct {
	mock *MockAccounts
}

// NewMockAccounts creates a new mock instance.
func NewMockAccounts(ctrl *gomock.Controller) *MockAccounts {
	mock := &MockAccounts{ctrl: ctrl}
	mock.recorder = &MockAccountsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccounts) EXPECT() *MockAccountsMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccounts) CreateAccount(ctx context.Context, a *domain.Account) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, a)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountsMockRecorder) CreateAccount(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccounts)(nil).CreateAccount), ctx, a)
}

// DeleteAccount mocks base method.
func (m *MockAccounts) DeleteAccount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockAccountsMockRecorder) DeleteAccount(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockAccounts)(nil).DeleteAccount), ctx, id)
}

// DepAccount mocks base method.
func (m *MockAccounts) DepAccount(ctx context.Context, dep domain.DepAccount, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepAccount", ctx, dep, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DepAccount indicates an expected call of DepAccount.
func (mr *MockAccountsMockRecorder) DepAccount(ctx, dep, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepAccount", reflect.TypeOf((*MockAccounts)(nil).DepAccount), ctx, dep, id)
}

// GetAccountByCurrency mocks base method.
func (m *MockAccounts) GetAccountByCurrency(ctx context.Context, id int64, currency string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByCurrency", ctx, id, currency)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByCurrency indicates an expected call of GetAccountByCurrency.
func (mr *MockAccountsMockRecorder) GetAccountByCurrency(ctx, id, currency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByCurrency", reflect.TypeOf((*MockAccounts)(nil).GetAccountByCurrency), ctx, id, currency)
}

// GetAccountByID mocks base method.
func (m *MockAccounts) GetAccountByID(ctx context.Context, id int64) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, id)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockAccountsMockRecorder) GetAccountByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockAccounts)(nil).GetAccountByID), ctx, id)
}

// GetAccounts mocks base method.
func (m *MockAccounts) GetAccounts(ctx context.Context, IDUser int64) ([]domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx, IDUser)
	ret0, _ := ret[0].([]domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MockAccountsMockRecorder) GetAccounts(ctx, IDUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockAccounts)(nil).GetAccounts), ctx, IDUser)
}

// UpdateAccount mocks base method.
func (m *MockAccounts) UpdateAccount(ctx context.Context, id, balance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, id, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockAccountsMockRecorder) UpdateAccount(ctx, id, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockAccounts)(nil).UpdateAccount), ctx, id, balance)
}
