// Package candidates provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package candidates

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	// Code Код ошибки приложения
	Code int32 `json:"code"`

	// Message Сообщение об ошибке
	Message string `json:"message"`

	// Status HTTP статус код
	Status int `json:"status"`
}

// GetTransferByID defines model for GetTransferByID.
type GetTransferByID struct {
	Transfer Transfer `json:"transfer"`
}

// GetTransfersResponse defines model for GetTransfersResponse.
type GetTransfersResponse struct {
	Transfers []Transfer `json:"transfers"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse = Error

// Transfer defines model for Transfer.
type Transfer struct {
	// Currency Валюта перевода
	Currency string `json:"currency"`
	Id       *int64 `json:"id,omitempty"`

	// IdFrom ID счета отправителя
	IdFrom int64 `json:"id_from"`

	// IdTo ID счета получателя
	IdTo int64 `json:"id_to"`

	// Value Сумма перевода
	Value int64 `json:"value"`
}

// Limit defines model for Limit.
type Limit = int32

// TransferId defines model for Transfer_id.
type TransferId = int64

// GetTransfersParams defines parameters for GetTransfers.
type GetTransfersParams struct {
	// Limit Ограничение количества переводов
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// MakeTransferJSONRequestBody defines body for MakeTransfer for application/json ContentType.
type MakeTransferJSONRequestBody = Transfer

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создание перевода
	// (POST /transfers)
	MakeTransfer(c *gin.Context)
	// Получение перевода по айди
	// (GET /transfers/by_id/{id})
	GetTransferByID(c *gin.Context, id TransferId)
	// Отмена перевода
	// (POST /transfers/last/{id})
	CancelTransfer(c *gin.Context, id TransferId)
	// Получение списка переводов
	// (GET /transfers/{id})
	GetTransfers(c *gin.Context, id TransferId, params GetTransfersParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// MakeTransfer operation middleware
func (siw *ServerInterfaceWrapper) MakeTransfer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MakeTransfer(c)
}

// GetTransferByID operation middleware
func (siw *ServerInterfaceWrapper) GetTransferByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TransferId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransferByID(c, id)
}

// CancelTransfer operation middleware
func (siw *ServerInterfaceWrapper) CancelTransfer(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TransferId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelTransfer(c, id)
}

// GetTransfers operation middleware
func (siw *ServerInterfaceWrapper) GetTransfers(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TransferId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransfersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTransfers(c, id, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/transfers", wrapper.MakeTransfer)
	router.GET(options.BaseURL+"/transfers/by_id/:id", wrapper.GetTransferByID)
	router.POST(options.BaseURL+"/transfers/last/:id", wrapper.CancelTransfer)
	router.GET(options.BaseURL+"/transfers/:id", wrapper.GetTransfers)
}
